# Generated by Django 5.1.3 on 2024-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
