# Generated by Django 5.1.3 on 2024-12-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0004_evidence_attorney_witness_attorney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='attorney',
            new_name='legalUser',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='attorney',
            new_name='legalUser',
        ),
    ]
