# Generated by Django 5.1.3 on 2024-12-12 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0007_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2024, django.core.validators.MinValueValidator(2009))]),
            preserve_default=False,
        ),
    ]
