# Generated by Django 5.1.3 on 2024-12-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0002_witness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='witness',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='evidence',
            name='category',
            field=models.CharField(blank=True, default='Category', max_length=30),
        ),
        migrations.AddField(
            model_name='witness',
            name='description',
            field=models.TextField(default='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='witness',
            name='testimony',
            field=models.TextField(blank=True, default='Testimony'),
        ),
    ]
