# Generated by Django 5.1.3 on 2024-12-11 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0006_alter_evidence_legaluser_alter_witness_legaluser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(blank=True, default='Verdict', max_length=30)),
                ('legalUser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
