# Generated by Django 5.1.3 on 2024-12-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0008_battle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='icon',
            field=models.ImageField(blank=True, upload_to='source_icon'),
        ),
        migrations.AddField(
            model_name='witness',
            name='icon',
            field=models.ImageField(blank=True, upload_to='source_icon'),
        ),
    ]
