# Generated by Django 5.1.3 on 2024-12-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0009_evidence_icon_witness_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='icon',
            field=models.ImageField(blank=True, upload_to='staticfiles/images/'),
        ),
        migrations.AlterField(
            model_name='witness',
            name='icon',
            field=models.ImageField(blank=True, upload_to='staticfiles/images/'),
        ),
    ]
