# Generated by Django 5.1.3 on 2024-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0011_alter_evidence_icon_alter_witness_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='witness',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
