# Generated by Django 5.1.3 on 2024-12-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courtrecord', '0013_alter_evidence_icon_alter_witness_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='year',
            field=models.IntegerField(),
        ),
    ]
